### ISSUE TITLE
Issue: width and height must be > 0

### ISSUE THREAD

**Issue by gauravk1** [parkpow/alpr-anpr-android#2]
Getting following crash on Image selection from gallery:

Process: com.glowingsoft.carplaterecognizer, PID: 17343
    java.lang.IllegalArgumentException: width and height must be > 0
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1150)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1117)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1067)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1028)
        at com.glowingsoft.carplaterecognizer.ui.MainActivity.compressImage(MainActivity.java:435)
        at com.glowingsoft.carplaterecognizer.ui.MainActivity.onPickResult(MainActivity.java:160)
        at com.vansuita.pickimage.dialog.PickImageBaseDialog$2.onFinish(PickImageBaseDialog.java:303)
        at com.vansuita.pickimage.async.AsyncImageResult.onPostExecute(AsyncImageResult.java:79)
        at com.vansuita.pickimage.async.AsyncImageResult.onPostExecute(AsyncImageResult.java:19)
        at android.os.AsyncTask.finish(AsyncTask.java:771)
        at android.os.AsyncTask.access$900(AsyncTask.java:199)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8506)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)

**Comment by ngethe** [comment]
Same error Did you @gauravk1  resolve this ?

**Comment by danleyb2** [comment]
@ngethe Are you get the same error with the latest version, Kindly make it easier to re-produce
